re-add --yes for proper backwards compatibility

diff --git a/alf b/alf
--- a/alf
+++ b/alf
@@ -82,12 +82,17 @@ alf_connect_usage() {
     # :command.usage_flags
     # :flag.usage
     echo "  --ssh"
-    printf "    Connect non-interactively using SSH\n"
+    printf "    Connect to GitHub non-interactively using SSH (implies --yes)\n"
     echo
     
     # :flag.usage
     echo "  --https"
-    printf "    Connect non-interactively using HTTPS\n"
+    printf "    Connect to GitHub non-interactively using HTTPS (implies --yes)\n"
+    echo
+    
+    # :flag.usage
+    echo "  --yes, -y"
+    printf "    Connect to any remote repository non-interactively\n"
     echo
     # :command.usage_args
     printf "Arguments:\n"
@@ -102,6 +107,7 @@ alf_connect_usage() {
     
     printf "  alf connect you --ssh\n"
     printf "  alf connect you/alf-config\n"
+    printf "  alf connect https://You@bitbucket.org/YourUser/rush-repo.git --yes\n"
     echo
 
   fi
@@ -443,6 +449,7 @@ save_config() {
 alf_connect_command() {
   # :src/connect_command.sh
   repo=${args[repo]}
+  force=${args[--yes]}
   force_ssh=${args[--ssh]}
   force_https=${args[--https]}
   
@@ -464,6 +471,16 @@ alf_connect_command() {
   elif [[ $force_https ]]; then
     answer=y
     [[ $partial_github_url ]] && repo_url="https://github.com/$repo_url"
+    echo "Connecting to $repo_url"
+  
+  elif [[ $force ]] ; then
+    if [[ $partial_github_url ]] ; then
+      echo "Error: Cannot determine the full URL for the repository"
+      echo "To connect to GitHub use --ssh or --https"
+      echo "To connect to another repository, provide the full URL"
+      exit 1
+    fi
+    answer=y
     echo "Connecting to $repo_url"
   
   else
@@ -766,6 +783,12 @@ alf_connect_parse_requirements() {
     # :flag.case
     --https )
       args[--https]=1
+      shift
+      ;;
+  
+    # :flag.case
+    --yes | -y )
+      args[--yes]=1
       shift
       ;;
   
@@ -1109,7 +1132,7 @@ alf_upgrade_parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="0.5.0"
+  version="0.4.2"
   long_usage=''
   set -e  
 
