- Generate with bashly 0.8.3

diff --git a/alf b/alf
--- a/alf
+++ b/alf
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 0.8.1 (https://bashly.dannyb.co)
+# This script was generated by bashly 0.8.3 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -45,8 +45,10 @@ alf_usage() {
   echo "  info       Show all alf related system facts"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
@@ -86,12 +88,15 @@ alf_connect_usage() {
   printf "  alf connect --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
     echo
+
     # :command.usage_flags
     # :flag.usage
     echo "  --ssh"
@@ -107,6 +112,7 @@ alf_connect_usage() {
     echo "  --yes, -y"
     printf "    Connect to any remote repository non-interactively\n"
     echo
+
     # :command.usage_args
     printf "Arguments:\n"
 
@@ -117,7 +123,6 @@ alf_connect_usage() {
 
     # :command.usage_examples
     printf "Examples:\n"
-
     printf "  alf connect you --ssh\n"
     printf "  alf connect you/alf-config\n"
     printf "  alf connect https://You@bitbucket.org/YourUser/rush-repo.git --yes\n"
@@ -146,8 +151,10 @@ alf_download_usage() {
   printf "  alf download --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
@@ -176,8 +183,10 @@ alf_upload_usage() {
   printf "  alf upload --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
@@ -206,8 +215,10 @@ alf_generate_usage() {
   printf "  alf generate --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
@@ -236,8 +247,10 @@ alf_save_usage() {
   printf "  alf save --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
@@ -274,8 +287,10 @@ alf_edit_usage() {
   printf "  alf edit --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
@@ -304,8 +319,10 @@ alf_which_usage() {
   printf "  alf which --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
@@ -344,8 +361,10 @@ alf_upgrade_usage() {
   printf "  alf upgrade --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
@@ -371,8 +390,10 @@ alf_info_usage() {
   printf "  alf info --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "Options:\n"
+
     # :command.usage_fixed_flags
     echo "  --help, -h"
     printf "    Show this help\n"
@@ -679,6 +700,7 @@ alf_connect_command() {
   fi
 
   save_config
+
 }
 
 # :command.function
@@ -722,12 +744,14 @@ alf_upload_command() {
 alf_generate_command() {
   # src/generate_command.sh
   generate_config
+
 }
 
 # :command.function
 alf_save_command() {
   # src/save_command.sh
   save_config
+
 }
 
 # :command.function
@@ -770,12 +794,14 @@ alf_which_command() {
 
   echo "Error: No such alias: $code $subcode"
   exit 1
+
 }
 
 # :command.function
 alf_upgrade_command() {
   # src/upgrade_command.sh
   exec bash <(curl -s https://raw.githubusercontent.com/DannyBen/alf/master/setup)
+
 }
 
 # :command.function
@@ -846,8 +872,7 @@ parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action=${1:-}
 
@@ -919,12 +944,18 @@ parse_requirements() {
     ;;
 
   # :command.command_fallback
-  * )
+  "" )
     alf_usage
     exit 1
     ;;
 
+  * )
+    printf "invalid command: %s\n" "$action"
+    exit 1
+    ;;
+
   esac
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -940,16 +971,12 @@ parse_requirements() {
       # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
+
       ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
@@ -963,17 +990,17 @@ alf_connect_parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action="connect"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
     # :flag.case
     --ssh )
-      # :flag.conflicts
+
       # :flag.case_no_arg
       args[--ssh]=1
       shift
@@ -981,7 +1008,7 @@ alf_connect_parse_requirements() {
 
     # :flag.case
     --https )
-      # :flag.conflicts
+
       # :flag.case_no_arg
       args[--https]=1
       shift
@@ -989,7 +1016,7 @@ alf_connect_parse_requirements() {
 
     # :flag.case
     --yes | -y )
-      # :flag.conflicts
+
       # :flag.case_no_arg
       args[--yes]=1
       shift
@@ -1004,13 +1031,14 @@ alf_connect_parse_requirements() {
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
       if [[ -z ${args[repo]+x} ]]; then
-        # :argument.validations
+
         args[repo]=$1
         shift
       else
         printf "invalid argument: %s\n" "$key"
         exit 1
       fi
+
       ;;
 
     esac
@@ -1020,11 +1048,7 @@ alf_connect_parse_requirements() {
     printf "missing required argument: REPO\nusage: alf connect REPO [options]\n"
     exit 1
   fi
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
@@ -1038,10 +1062,10 @@ alf_download_parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action="download"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1057,16 +1081,12 @@ alf_download_parse_requirements() {
       # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
+
       ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
@@ -1080,10 +1100,10 @@ alf_upload_parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action="upload"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1099,16 +1119,12 @@ alf_upload_parse_requirements() {
       # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
+
       ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
@@ -1122,10 +1138,10 @@ alf_generate_parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action="generate"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1141,16 +1157,12 @@ alf_generate_parse_requirements() {
       # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
+
       ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
@@ -1164,10 +1176,10 @@ alf_save_parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action="save"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1183,16 +1195,12 @@ alf_save_parse_requirements() {
       # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
+
       ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
@@ -1206,10 +1214,10 @@ alf_edit_parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action="edit"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1225,16 +1233,12 @@ alf_edit_parse_requirements() {
       # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
+
       ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
@@ -1248,10 +1252,10 @@ alf_which_parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action="which"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1266,17 +1270,18 @@ alf_which_parse_requirements() {
       # :command.parse_requirements_case
       # :command.parse_requirements_case_simple
       if [[ -z ${args[code]+x} ]]; then
-        # :argument.validations
+
         args[code]=$1
         shift
       elif [[ -z ${args[subcode]+x} ]]; then
-        # :argument.validations
+
         args[subcode]=$1
         shift
       else
         printf "invalid argument: %s\n" "$key"
         exit 1
       fi
+
       ;;
 
     esac
@@ -1286,11 +1291,7 @@ alf_which_parse_requirements() {
     printf "missing required argument: CODE\nusage: alf which CODE [SUBCODE]\n"
     exit 1
   fi
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
@@ -1304,10 +1305,10 @@ alf_upgrade_parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action="upgrade"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1323,16 +1324,12 @@ alf_upgrade_parse_requirements() {
       # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
+
       ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.parse_requirements
@@ -1346,10 +1343,10 @@ alf_info_parse_requirements() {
     ;;
 
   esac
-  # :command.environment_variables_filter
-  # :command.dependencies_filter
+
   # :command.command_filter
   action="info"
+
   # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1365,16 +1362,12 @@ alf_info_parse_requirements() {
       # :command.parse_requirements_case_simple
       printf "invalid argument: %s\n" "$key"
       exit 1
+
       ;;
 
     esac
   done
-  # :command.required_args_filter
-  # :command.required_flags_filter
-  # :command.catch_all_filter
-  # :command.default_assignments
-  # :command.whitelist_filter
-  # :command.user_filter
+
 }
 
 # :command.initialize
@@ -1387,6 +1380,7 @@ initialize() {
   aliases_file=${ALF_ALIASES_FILE:-~/.bash_aliases}
   rc_file=${ALF_RC_FILE:-~/.alfrc}
   set -e
+
 }
 
 # :command.run
