move commands to subfolder

diff --git a/alf b/alf
--- a/alf
+++ b/alf
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.7 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.3.6 (https://bashly.dev)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
-if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
-  printf "bash version 4 or higher is required\n" >&2
+if ((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 2))); then
+  printf "bash version 4.2 or higher is required\n" >&2
   exit 1
 fi
 
@@ -39,13 +39,14 @@ alf_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
-    printf "  %s\n" "--version, -v"
+    printf "  %s\n" "$(bold "--version, -v")"
     printf "    Show version number\n"
     echo
 
@@ -53,7 +54,7 @@ alf_usage() {
     printf "%s\n" "$(bold "Environment Variables:")"
 
     # :environment_variable.usage
-    printf "  %s\n" "ALF_RC_FILE"
+    printf "  %s\n" "$(bold "ALF_RC_FILE")"
     printf "    Path to alfrc file.\n    \n    This file holds the path to the alf-conf repository.\n    \n    Default: \`~/.alfrc\`\n"
     echo
 
@@ -73,26 +74,27 @@ alf_connect_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_flags
     # :flag.usage
-    printf "  %s\n" "--ssh"
+    printf "  %s\n" "$(bold "--ssh")"
     printf "    Connect to GitHub non-interactively using SSH (implies \`--yes\`).\n"
     echo
 
     # :flag.usage
-    printf "  %s\n" "--https"
+    printf "  %s\n" "$(bold "--https")"
     printf "    Connect to GitHub non-interactively using HTTPS (implies \`--yes\`).\n"
     echo
 
     # :flag.usage
-    printf "  %s\n" "--yes, -y"
+    printf "  %s\n" "$(bold "--yes, -y")"
     printf "    Connect to any remote repository non-interactively.\n"
     echo
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -100,7 +102,7 @@ alf_connect_usage() {
     printf "%s\n" "$(bold "Arguments:")"
 
     # :argument.usage
-    printf "  %s\n" "REPO"
+    printf "  %s\n" "$(bold "REPO")"
     printf "    Remote GitHub repository to connect to.\n    \n    Can be one of:\n    \n    - Your username on GitHub.\n      In this case, the repository is expected to be named \`alf-conf\`.\n    - Your username/repo on GitHub.\n    - Any other full URL to a repository.\n"
     echo
 
@@ -127,10 +129,11 @@ alf_download_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -150,10 +153,11 @@ alf_upload_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -173,10 +177,11 @@ alf_generate_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -196,10 +201,11 @@ alf_save_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -207,7 +213,7 @@ alf_save_usage() {
     printf "%s\n" "$(bold "Environment Variables:")"
 
     # :environment_variable.usage
-    printf "  %s\n" "ALF_ALIASES_FILE"
+    printf "  %s\n" "$(bold "ALF_ALIASES_FILE")"
     printf "    Path to bash_aliases file.\n    \n    Aliases will be saved to this file.\n    \n    Default: \`~/.bash_aliases\`\n"
     echo
 
@@ -227,10 +233,11 @@ alf_edit_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -250,10 +257,11 @@ alf_which_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -261,12 +269,12 @@ alf_which_usage() {
     printf "%s\n" "$(bold "Arguments:")"
 
     # :argument.usage
-    printf "  %s\n" "CODE"
+    printf "  %s\n" "$(bold "CODE")"
     printf "    Show the command for this alias code.\n"
     echo
 
     # :argument.usage
-    printf "  %s\n" "SUBCODE"
+    printf "  %s\n" "$(bold "SUBCODE")"
     printf "    Show the command for this alias sub-code.\n"
     echo
 
@@ -284,10 +292,11 @@ alf_upgrade_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -305,10 +314,11 @@ alf_info_usage() {
 
   # :command.long_usage
   if [[ -n "$long_usage" ]]; then
+    # :command.usage_options
     printf "%s\n" "$(bold "Options:")"
 
     # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
+    printf "  %s\n" "$(bold "--help, -h")"
     printf "    Show this help\n"
     echo
 
@@ -349,6 +359,8 @@ normalize_input() {
 
 # :command.inspect_args
 inspect_args() {
+  local k
+
   if ((${#args[@]})); then
     readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
     echo args:
@@ -579,7 +591,7 @@ save_config() {
 # :command.function
 alf_connect_command() {
 
-  # src/connect_command.sh
+  # src/commands/connect.sh
   repo=${args[repo]}
   force=${args[--yes]}
   force_ssh=${args[--ssh]}
@@ -670,7 +682,7 @@ alf_connect_command() {
 # :command.function
 alf_download_command() {
 
-  # src/download_command.sh
+  # src/commands/download.sh
   find_config
 
   if [[ ! -f $rc_file ]]; then
@@ -690,7 +702,7 @@ alf_download_command() {
 # :command.function
 alf_upload_command() {
 
-  # src/upload_command.sh
+  # src/commands/upload.sh
   find_config
 
   if [[ ! -f $rc_file ]]; then
@@ -709,7 +721,7 @@ alf_upload_command() {
 # :command.function
 alf_generate_command() {
 
-  # src/generate_command.sh
+  # src/commands/generate.sh
   generate_config
 
 }
@@ -717,7 +729,7 @@ alf_generate_command() {
 # :command.function
 alf_save_command() {
 
-  # src/save_command.sh
+  # src/commands/save.sh
   save_config
 
 }
@@ -725,7 +737,7 @@ alf_save_command() {
 # :command.function
 alf_edit_command() {
 
-  # src/edit_command.sh
+  # src/commands/edit.sh
   find_config
   ${EDITOR:-vi} "$config_file"
 }
@@ -733,7 +745,7 @@ alf_edit_command() {
 # :command.function
 alf_which_command() {
 
-  # src/which_command.sh
+  # src/commands/which.sh
   code=${args[code]}
   subcode=${args[subcode]}
 
@@ -770,7 +782,7 @@ alf_which_command() {
 # :command.function
 alf_upgrade_command() {
 
-  # src/upgrade_command.sh
+  # src/commands/upgrade.sh
   exec bash <(curl -s https://raw.githubusercontent.com/DannyBen/alf/master/setup)
 
 }
@@ -778,7 +790,7 @@ alf_upgrade_command() {
 # :command.function
 alf_info_command() {
 
-  # src/info_command.sh
+  # src/commands/info.sh
   find_config
 
   if [[ -d "$repo_path/.git" ]]; then
@@ -830,6 +842,8 @@ alf_info_command() {
 
 # :command.parse_requirements
 parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -961,6 +975,8 @@ parse_requirements() {
 
 # :command.parse_requirements
 alf_connect_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1054,6 +1070,8 @@ alf_connect_parse_requirements() {
 
 # :command.parse_requirements
 alf_download_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1111,6 +1129,8 @@ alf_download_parse_requirements() {
 
 # :command.parse_requirements
 alf_upload_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1168,6 +1188,8 @@ alf_upload_parse_requirements() {
 
 # :command.parse_requirements
 alf_generate_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1213,6 +1235,8 @@ alf_generate_parse_requirements() {
 
 # :command.parse_requirements
 alf_save_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1260,6 +1284,8 @@ alf_save_parse_requirements() {
 
 # :command.parse_requirements
 alf_edit_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1305,6 +1331,8 @@ alf_edit_parse_requirements() {
 
 # :command.parse_requirements
 alf_which_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1367,6 +1395,8 @@ alf_which_parse_requirements() {
 
 # :command.parse_requirements
 alf_upgrade_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1424,6 +1454,8 @@ alf_upgrade_parse_requirements() {
 
 # :command.parse_requirements
 alf_info_parse_requirements() {
+  local key
+
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     key="$1"
@@ -1481,13 +1513,8 @@ alf_info_parse_requirements() {
 
 # :command.initialize
 initialize() {
-  version="0.6.1"
-  long_usage=''
+  declare -g version="0.6.1"
   set -e
-
-  # :command.globals
-  declare -g -A args=()
-  declare -g -a input=()
 
   # src/initialize.sh
   aliases_file=${ALF_ALIASES_FILE:-~/.bash_aliases}
@@ -1498,6 +1525,11 @@ initialize() {
 
 # :command.run
 run() {
+  # :command.globals
+  declare -g long_usage=''
+  declare -g -A args=()
+  declare -g -a input=()
+
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
@@ -1515,6 +1547,8 @@ run() {
 }
 
 if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+  # :command.start
+  command_line_args=("$@")
   initialize
-  run "$@"
+  run "${command_line_args[@]}"
 fi
