- Add alf info command

diff --git a/alf b/alf
--- a/alf
+++ b/alf
@@ -32,6 +32,7 @@ alf_usage() {
   echo "  edit       Open your alf.conf for editing"
   echo "  which      Show the alias command"
   echo "  upgrade    Upgrade alf to the latest version"
+  echo "  info       Show all alf related system facts"
   echo
 
   if [[ -n $long_usage ]]; then
@@ -327,6 +328,31 @@ alf_upgrade_usage() {
   fi
 }
 
+# :command.usage
+alf_info_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "alf info - Show all alf related system facts\n"
+    echo 
+  else
+    printf "alf info - Show all alf related system facts\n"
+    echo 
+  fi
+
+  printf "Usage:\n"
+  printf "  alf info\n"
+  printf "  alf info --help | -h\n"
+  echo
+
+  if [[ -n $long_usage ]]; then
+    printf "Options:\n"
+    # :command.usage_fixed_flags
+    echo "  --help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
 # :command.inspect_args
 inspect_args() {
   echo args:
@@ -334,6 +360,40 @@ inspect_args() {
 }
 
 # :command.user_lib
+# :src/lib/colors.sh
+# ---
+# Color functions
+# This file is a part of Bashly standard library
+#
+# Usage:
+# Use any of the functions below to color or format a portion of a string.
+# 
+#   echo "before $(red this is red) after"
+#   echo "before $(green_bold this is green_bold) after"
+#
+# ---
+
+red() { printf "\e[31m%b\e[0m\n" "$*"; }
+green() { printf "\e[32m%b\e[0m\n" "$*"; }
+yellow() { printf "\e[33m%b\e[0m\n" "$*"; }
+blue() { printf "\e[34m%b\e[0m\n" "$*"; }
+magenta() { printf "\e[35m%b\e[0m\n" "$*"; }
+cyan() { printf "\e[36m%b\e[0m\n" "$*"; }
+bold() { printf "\e[1m%b\e[0m\n" "$*"; }
+underlined() { printf "\e[4m%b\e[0m\n" "$*"; }
+red_bold() { printf "\e[1;31m%b\e[0m\n" "$*"; }
+green_bold() { printf "\e[1;32m%b\e[0m\n" "$*"; }
+yellow_bold() { printf "\e[1;33m%b\e[0m\n" "$*"; }
+blue_bold() { printf "\e[1;34m%b\e[0m\n" "$*"; }
+magenta_bold() { printf "\e[1;35m%b\e[0m\n" "$*"; }
+cyan_bold() { printf "\e[1;36m%b\e[0m\n" "$*"; }
+red_underlined() { printf "\e[4;31m%b\e[0m\n" "$*"; }
+green_underlined() { printf "\e[4;32m%b\e[0m\n" "$*"; }
+yellow_underlined() { printf "\e[4;33m%b\e[0m\n" "$*"; }
+blue_underlined() { printf "\e[4;34m%b\e[0m\n" "$*"; }
+magenta_underlined() { printf "\e[4;35m%b\e[0m\n" "$*"; }
+cyan_underlined() { printf "\e[4;36m%b\e[0m\n" "$*"; }
+
 # :src/lib/find_config.sh
 find_config() {
   repo_path="$PWD/alf-conf"
@@ -665,6 +725,22 @@ alf_upgrade_command() {
   exec bash <(curl -s https://raw.githubusercontent.com/DannyBen/alf/master/setup)
 }
 
+# :command.function
+alf_info_command() {
+  # :src/info_command.sh
+  inforow() {
+    printf "%-30s %s\n" "$1:" "$(green "$2")"
+  }
+  
+  find_config
+  
+  inforow "executable / path" "$(which alf)"
+  inforow "env / ALF_RC_FILE" "${ALF_RC_FILE:-unset}"
+  inforow "env / ALF_ALIASES_FILE" "${ALF_ALIASES_FILE:-unset}"
+  inforow "repo / path" "$repo_path"
+  inforow "config / path" "$config_file"
+}
+
 # :command.parse_requirements
 parse_requirements() {
   # :command.fixed_flag_filter
@@ -743,6 +819,13 @@ parse_requirements() {
     action="upgrade"
     shift
     alf_upgrade_parse_requirements "$@"
+    shift $#
+    ;;    
+  
+  info )
+    action="info"
+    shift
+    alf_info_parse_requirements "$@"
     shift $#
     ;;    
   
@@ -1164,6 +1247,49 @@ alf_upgrade_parse_requirements() {
   # :command.default_assignments
 }
 
+# :command.parse_requirements
+alf_info_parse_requirements() {
+  # :command.fixed_flag_filter
+  case "$1" in
+  --version | -v )
+    version_command
+    exit
+    ;;
+  
+  --help | -h )
+    long_usage=yes
+    alf_info_usage
+    exit 1
+    ;;
+  
+  esac
+  # :command.environment_variables_filter
+  # :command.dependencies_filter
+  # :command.command_filter
+  action="info"
+  # :command.required_args_filter
+  # :command.required_flags_filter
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+  
+    -* )
+      printf "invalid option: %s\n" "$key"
+      exit 1
+      ;;
+  
+    * )
+      # :command.parse_requirements_case
+      printf "invalid argument: %s\n" "$key"
+      exit 1
+      ;;
+  
+    esac
+  done
+  # :command.default_assignments
+}
+
 # :command.initialize
 initialize() {
   version="0.4.4"
@@ -1243,6 +1369,14 @@ run() {
       alf_upgrade_usage
     else
       alf_upgrade_command
+    fi
+  
+  elif [[ $action == "info" ]]; then
+    if [[ ${args[--help]} ]]; then
+      long_usage=yes
+      alf_info_usage
+    else
+      alf_info_command
     fi
   
   elif [[ ${args[--version]} ]]; then
